In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from skmultilearn.adapt import MLkNN
import sklearn.metrics as metrics
from sklearn.metrics import hamming_loss, accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import multilabel_confusion_matrix
import os

In [2]:
d2= pd.read_csv('train_ta_l1.csv')
d2
d2 = d2.rename(columns={'key' : 'unique_id', 'sentence' : 'text'})
d2.to_csv('updated_train_ta_l1.csv', index=False)
# d2

# Convert annotator columns to numeric without replacing NaNs
d2[['ta_a1', 'ta_a2', 'ta_a3', 'ta_a4', 'ta_a5', 'ta_a6']] = d2[
    ['ta_a1', 'ta_a2', 'ta_a3', 'ta_a4', 'ta_a5', 'ta_a6']
].apply(pd.to_numeric, errors='coerce')  # NaNs are retained

# Compute 'label' based on majority voting while ignoring NaNs
d2['label'] = (
    d2[['ta_a1', 'ta_a2', 'ta_a3', 'ta_a4', 'ta_a5', 'ta_a6']].mean(axis=1, skipna=True) >= 0.5
).astype(int)

d2

text   unique_id  ta_a1  \
0        *1. முரசொலி அலுவலகம் அமைந்துள்ள இடம் பஞ்சமி...  question_1    NaN   
1        சோத்துக்கு பிச்சை எடுக்கிற கடங்கார நாய்களுக...  question_1    NaN   
2              தத்தபுத்த தத்தபுத்த ன்னு எதாவது புரியுதா  question_1    NaN   
3         பச்சை மொளகா காரம் vicky அம்மா புண்டை நாறும் 😆  question_1    NaN   
4       என்ன உடம்பு டா சாமி- சும்மா வளுவளுனு.. முலை ...  question_1    1.0   
...                                                 ...         ...    ...   
6774                      😭😭😭 ஒம்மாள படிக்கல் புண்ட 😭😭😭  question_1    NaN   
6775  🙄🙄🙄🙄 என்ன எழவுயா இது...   இதெல்லாம் ஒரு பெருமை...  question_1    NaN   
6776  🚨எக்ஸ் பிரஸ் பேர்ல் கப்பல் தீ விபத்துக்கு உள்ள...  question_1    NaN   
6777  🤣 🤣 சல்லி ஜாதி வெறி முட்டா புண்ட உங்க பொண்ணுங்...  question_1    NaN   
6778  🤣🤣🤣 நீ சொல்றது எல்லாமும் அந்த திம்கவோட தம்பி  ...  question_1    NaN   

      ta_a2  ta_a3  ta_a4  ta_a5  ta_a6  label  
0       NaN    0.0    0.0    0.0    0.0      0  
1       NaN    NaN    0.0    NaN    NaN      0  
2       NaN    NaN    NaN    0.0    NaN      0  
3       NaN    NaN    NaN    1.0    NaN      1  
4       NaN    NaN    NaN    NaN    NaN      1  
...     ...    ...    ...    ...    ...    ...  
6774    NaN    1.0    NaN    NaN    NaN      1  
6775    NaN    NaN    NaN    0.0    NaN      0  
6776    0.0    NaN    NaN    NaN    NaN      0  
6777    0.0    NaN    NaN    NaN    NaN      0  
6778    NaN    1.0    NaN    NaN    NaN      1  

[6779 rows x 9 columns]

In [3]:
# Create binary label ('hate' or 'not_hate')
def determine_binary_label(label):
    return 'hate' if label == 1 else 'not_hate'

d2['binary_label'] = d2['label'].apply(determine_binary_label)

# # Reorder columns
d2 = d2[['unique_id', 'text', 'binary_label', 'label']]

In [4]:
d2.to_csv('updated_train_ta_l1.csv', index=False)

In [5]:
import nltk
import string
import re

def normalize_text(text):
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"
                               u"\U0001F300-\U0001F5FF"
                               u"\U0001F680-\U0001F6FF"
                               u"\U0001F700-\U0001F77F"
                               u"\U0001F780-\U0001F7FF"
                               u"\U0001F800-\U0001F8FF"
                               u"\U0001F900-\U0001F9FF"
                               u"\U0001FA00-\U0001FA6F"
                               u"\U0001FA70-\U0001FAFF"
                               u"\U00002702-\U000027B0"
                               u"\U000024C2-\U0001F251"
                               "]+", flags=re.UNICODE)
    text = text.lower()
    text = re.sub(r'\[.*?\]', ' ', text)
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)
    text = re.sub(r'<.*?>+', ' ', text)
    text = re.sub(r'[%s]' % re.escape(string.punctuation), ' ', text)
    text = re.sub(r'\n', ' ', text)
    text = re.sub(r'\w*\d\w*', ' ', text)
    text = re.sub(r'<handle replaced>', '', text)
    text = emoji_pattern.sub(r'', text)
    return text

## Apply the written function ##
d2.loc[:, 'text'] = d2['text'].apply(lambda x: normalize_text(x))
processed_list = []
for j in d2['text']:
    process = j.replace('...','')
    processed_list.append(process)

df_processed = pd.DataFrame(processed_list)
df_processed.columns = ['text']
df_processed.head(n=5)

text
0         முரசொலி அலுவலகம் அமைந்துள்ள இடம் பஞ்சமி...
1     சோத்துக்கு பிச்சை எடுக்கிற கடங்கார நாய்களுக...
2           தத்தபுத்த தத்தபுத்த ன்னு எதாவது புரியுதா
3       பச்சை மொளகா காரம் vicky அம்மா புண்டை நாறும் 
4    என்ன உடம்பு டா சாமி  சும்மா வளுவளுனு   முலை ...

In [6]:
X = list(df_processed['text'])
y = d2[['label']].values
y

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]], shape=(6779, 1))

In [7]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import (
    LSTM, Activation, Dropout, Dense, Flatten,
    Bidirectional, GRU, concatenate, SpatialDropout1D,
    GlobalMaxPooling1D, GlobalAveragePooling1D, Conv1D,
    Embedding, Input, Concatenate
)
from tensorflow.keras.optimizers import Adam, SGD, RMSprop
from tensorflow.keras.losses import MeanSquaredError

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

######## Textual Features for Embedding ###################
max_len = 100
max_features = 4479

# Tokenization
tokenizer = Tokenizer(num_words=max_features)
tokenizer.fit_on_texts(X)
X = tokenizer.texts_to_sequences(X)

# Padding
X = pad_sequences(X, padding='post', maxlen=max_len)

print(X)  # Check the processed sequences

[[1557 2466  444 ...    0    0    0]
 [1396  323 2468 ...    0    0    0]
 [ 135  520 2470 ...    0    0    0]
 ...
 [3879 2142 1100 ...    0    0    0]
 [ 406  430  602 ...    0    0    0]
 [   4  850   13 ...    0    0    0]]


In [8]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y.ravel())
y

array([0, 0, 0, ..., 0, 0, 1], shape=(6779,))

In [9]:
from keras.utils import to_categorical
y = to_categorical(y, num_classes=2)
y

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]], shape=(6779, 2))

In [10]:
d2.loc[:, 'binary_label'] = d2['label'].apply(determine_binary_label)

# # Reorder columns
d2 = d2[['unique_id', 'text', 'binary_label', 'label']]

d2.to_csv('updated_test_en_l1.csv', index=False)

d2.loc[:, 'text'] = d2['text'].apply(lambda x: normalize_text(x))
processed_list = []
for j in d2['text']:
    process = j.replace('...','')
    processed_list.append(process)

df_processed = pd.DataFrame(processed_list)
df_processed.columns = ['text']
df_processed.head(n=5)

X = list(df_processed['text'])
y = d2[['label']].values

X = tokenizer.texts_to_sequences(X)

# Padding
X = pad_sequences(X, padding='post', maxlen=max_len)

y = label_encoder.fit_transform(y.ravel())

y = to_categorical(y, num_classes=2)


In [11]:
import numpy as np
import json

# Load GloVe embeddings from JSON
with open('glove_embeddings.json', encoding="utf8") as f:
    embeddings_list = json.load(f)

# Convert the list of vectors to a dictionary with word indices as keys
embeddings_dictionary = {str(i): vector for i, vector in enumerate(embeddings_list)}

# Define tokenizer 
vocab_size = len(tokenizer.word_index) + 1  # Vocabulary size
word_index = tokenizer.word_index
num_words = min(max_features, vocab_size)  # Limit vocab to max_features

# Get embedding dimension (from first vector in list)
embed_size = len(embeddings_list[0]) if embeddings_list else 0

# Initialize embedding matrix
embedding_matrix = np.zeros((num_words, embed_size))

# Fill embedding matrix with corresponding word vectors
for word, index in word_index.items():
    if index >= max_features:
        continue
    embedding_vector = embeddings_dictionary.get(word) or embeddings_dictionary.get(str(index))
    if embedding_vector is not None:
        embedding_matrix[index] = np.asarray(embedding_vector, dtype=np.float32)

print("Embedding matrix shape:", embedding_matrix.shape)

Embedding matrix shape: (4479, 50)


In [12]:
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.layers import (
    Input, Embedding, SpatialDropout1D, Conv1D,
    Bidirectional, LSTM, Dense, Dropout,
    GlobalAveragePooling1D
)
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from sklearn.metrics import classification_report, f1_score, precision_score, recall_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Configure GPU for optimal performance
def configure_gpu():
    gpus = tf.config.list_physical_devices('GPU')
    if gpus:
        try:
            # Enable memory growth for each GPU
            for gpu in gpus:
                tf.config.experimental.set_memory_growth(gpu, True)
            logical_gpus = tf.config.list_logical_devices('GPU')
            print(f"{len(gpus)} Physical GPUs, {len(logical_gpus)} Logical GPUs")
            # Use mixed precision for better performance
            policy = tf.keras.mixed_precision.Policy('mixed_float16')
            tf.keras.mixed_precision.set_global_policy(policy)
            print('Mixed precision enabled')
        except RuntimeError as e:
            print(e)

configure_gpu()

# Model Definition
def create_cnn_bilstm_model(max_len, max_features, embedding_matrix, embed_size=300):
    """
    Creates the CNN-BiLSTM model architecture as described in the paper
    """
    # Input layer
    input_layer = Input(shape=(max_len,))
    
    # Embedding layer with pretrained weights (GloVe/FastText)
    embedding_layer = Embedding(
        input_dim=max_features,
        output_dim=embed_size,
        weights=[embedding_matrix],
        input_length=max_len,
        trainable=False  # As per paper, embeddings are non-trainable
    )(input_layer)
    
    # Spatial Dropout to prevent overfitting (as mentioned in paper)
    spatial_dropout = SpatialDropout1D(0.2)(embedding_layer)
    
    # CNN Layer (as described in paper)
    conv_layer = Conv1D(
        filters=64,  # As per paper
        kernel_size=2,  # As per paper
        activation='relu',
        padding='same'
    )(spatial_dropout)
    
    # Bidirectional LSTM Layer (as described in paper)
    bilstm_layer = Bidirectional(
        LSTM(
            units=128,  # As per paper
            return_sequences=True,
            dropout=0.1,  # As per paper
            recurrent_dropout=0.1  # As per paper
        )
    )(conv_layer)
    
    # Global Average Pooling (as per paper)
    gap_layer = GlobalAveragePooling1D()(bilstm_layer)
    
    # Dense layer (as per paper)
    dense_layer = Dense(128, activation='relu')(gap_layer)
    dropout_layer = Dropout(0.1)(dense_layer)  # Additional dropout as per paper
    
    # Output layer (use float32 for softmax for numerical stability)
    output_layer = Dense(2, activation='softmax', dtype='float32')(dropout_layer)
    
    # Create model
    model = Model(inputs=input_layer, outputs=output_layer)
    
    return model

# Custom macroF1 Score Metric
class MacroF1Score(tf.keras.metrics.Metric):
    def __init__(self, num_classes = 2, name='macro_f1_score', **kwargs):
        super(MacroF1Score, self).__init__(name=name, **kwargs)
        self.num_classes = num_classes
        self.tp = self.add_weight(name='tp', initializer='zeros')
        self.fp = self.add_weight(name='fp', initializer='zeros')
        self.fn = self.add_weight(name='fn', initializer='zeros')
        self.count = self.add_weight(name='count', initializer='zeros')

    def update_state(self, y_true, y_pred, sample_weight=None):
        # Convert probabilities to predicted class indices
        y_pred = tf.argmax(y_pred, axis=-1)
        
        # Convert one-hot encoded y_true to class indices if needed
        if len(y_true.shape) > 1 and y_true.shape[-1] > 1:
            y_true = tf.argmax(y_true, axis=-1)
        
        # Initialize confusion matrix
        conf_matrix = tf.math.confusion_matrix(
            y_true,
            y_pred,
            num_classes=self.num_classes,
            dtype=tf.float32
        )
        
        # Calculate TP, FP, FN for each class
        diag = tf.linalg.diag_part(conf_matrix)
        row_sum = tf.reduce_sum(conf_matrix, axis=1)
        col_sum = tf.reduce_sum(conf_matrix, axis=0)
        
        tp = diag
        fp = col_sum - diag
        fn = row_sum - diag
        
        # Update the state variables
        self.tp.assign_add(tf.reduce_sum(tp))
        self.fp.assign_add(tf.reduce_sum(fp))
        self.fn.assign_add(tf.reduce_sum(fn))
        self.count.assign_add(tf.cast(tf.shape(y_true)[0], tf.float32))

    def result(self):
        # Calculate precision and recall
        precision = self.tp / (self.tp + self.fp + tf.keras.backend.epsilon())
        recall = self.tp / (self.tp + self.fn + tf.keras.backend.epsilon())
        
        # Calculate F1 score
        f1 = 2 * (precision * recall) / (precision + recall + tf.keras.backend.epsilon())
        
        # Return macro F1 (average of per-class F1 scores)
        return f1

    def reset_states(self):
        self.tp.assign(0.)
        self.fp.assign(0.)
        self.fn.assign(0.)
        self.count.assign(0.)
            
# Model Training
def train_and_validate_model(model, X_train, y_train, X_val, y_val, batch_size=32, epochs=15, model_dir='models_ta_task1_m1'):
    """
    Trains the CNN-BiLSTM model with early stopping and model checkpointing
    Returns the best model and training history
    """
    # Create directory for saving models if it doesn't exist
    os.makedirs(model_dir, exist_ok=True)
    
    # Callbacks
    early_stopping = EarlyStopping(
        monitor='macro_f1_score',
        patience=2,
        restore_best_weights=True,
        mode='max',
        verbose=1
    )
    
    model_checkpoint = ModelCheckpoint(
        os.path.join(model_dir, 'best_model_ta_task1_m1.h5'),  # Save entire model
        monitor='macro_f1_score',
        mode='max',
        save_best_only=True,
        verbose=1
    )
    
    # Compile model with Adam optimizer (as per paper)
    model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss='categorical_crossentropy',
        metrics=['accuracy', MacroF1Score(num_classes=2)]
    )
    
    # Train the model
    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        batch_size=batch_size,
        epochs=epochs,
        callbacks=[early_stopping, model_checkpoint],
        verbose=1
    )
    
    # Load the best model found during training
    best_model = load_model(os.path.join(model_dir, 'best_model_ta_task1_m1.h5'), 
                          custom_objects={'MacroF1Score': MacroF1Score})
    
    return history, best_model

# Plot Training History
def plot_training_history(history, plot_dir='plots_nlp_project_ta_task1_m1'):
    """
    Plots training history (accuracy and loss curves)
    Saves plots to specified directory
    """
    os.makedirs(plot_dir, exist_ok=True)
    
    # Plot training history
    plt.figure(figsize=(12, 5))
    
    # Plot accuracy
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
    plt.title('Model Accuracy')
    plt.ylabel('Accuracy')
    plt.xlabel('Epoch')
    plt.legend()
    
    # Plot loss
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.title('Model Loss')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend()
    
    plt.tight_layout()
    plt.savefig(os.path.join(plot_dir, 'training_history_ta_task1.png'))
    plt.close()

# Validation Evaluation
def evaluate_validation(model, X_val, y_val, plot_dir='plots_nlp_project_ta_task1_m1'):
    """
    Evaluates the model on validation data and saves metrics and plots
    """
    os.makedirs(plot_dir, exist_ok=True)
    
    # Predict probabilities
    y_pred_proba = model.predict(X_val, batch_size=32)
    
    # Convert to class labels
    y_pred = np.argmax(y_pred_proba, axis=1)
    y_true = np.argmax(y_val, axis=1)
    
    # Calculate metrics
    precision = precision_score(y_true, y_pred, average='weighted')
    recall = recall_score(y_true, y_pred, average='weighted')
    weighted_f1 = f1_score(y_true, y_pred, average='weighted')
    macro_f1 = f1_score(y_true, y_pred, average='macro')

    
    # Classification report
    report = classification_report(y_true, y_pred, target_names=['not_hate', 'hate'])
    
    # Confusion matrix
    conf_matrix = confusion_matrix(y_true, y_pred)
    
    # Plot confusion matrix
    plt.figure(figsize=(8, 6))
    sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Not Hate', 'Hate'],
                yticklabels=['Not Hate', 'Hate'])
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.title('Confusion Matrix (Validation)')
    plt.savefig(os.path.join(plot_dir, 'confusion_matrix_val_ta_task1.png'))
    plt.close()
    
    return {
        'precision': precision,
        'recall': recall,
        'f1_score_weighted': weighted_f1,
        'f1_score_macro': macro_f1,
        'classification_report': report,
        'confusion_matrix': conf_matrix
    }


# Main Execution for Training and Validation
if __name__ == "__main__":
    # Split into train (80%) and validation (20%)
    
    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=0.2, random_state=42
    )
    
    print(f"Training samples: {len(X_train)}")
    print(f"Validation samples: {len(X_val)}")
    
    # Create model
    embed_size = embedding_matrix.shape[1]
    model = create_cnn_bilstm_model(max_len, max_features, embedding_matrix, embed_size)
    
    # Print model summary
    model.summary()
    
    # Train model (5 epochs as per paper)
    history, trained_model = train_and_validate_model(
        model, X_train, y_train, X_val, y_val,
        batch_size=32,  # As per paper for Tasks 1 & 3
        epochs=15  
    )
    
    # Plot training history
    plot_training_history(history)
    
    # Evaluate on validation set
    val_results = evaluate_validation(trained_model, X_val, y_val)
    
    print("\nValidation Results:")
    print(f"Precision: {val_results['precision']:.4f}")
    print(f"Recall: {val_results['recall']:.4f}")
    print(f"weighted F1 Score: {val_results['f1_score_weighted']:.4f}")
    print(f"macro F1 Score: {val_results['f1_score_macro']:.4f}")
    print("\nClassification Report:")
    print(val_results['classification_report'])

Training samples: 5423
Validation samples: 1356


C:\Users\krmri\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (None, 100)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ embedding (Embedding)                │ (None, 100, 50)             │         223,950 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ spatial_dropout1d (SpatialDropout1D) │ (None, 100, 50)             │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d (Conv1D)                      │ (None, 100, 64)             │           6,464 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ bidirectional (Bidirectional)        │ (None, 100, 256)            │         197,632 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ global_average_pooling1d             │ (None, 256)                 │               0 │
│ (GlobalAveragePooling1D)             │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 2)                   │             258 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 461,200 (1.76 MB)

 Trainable params: 237,250 (926.76 KB)

 Non-trainable params: 223,950 (874.80 KB)

Epoch 1/15
170/170 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.5531 - loss: 0.6887 - macro_f1_score: 0.5531  
Epoch 1: macro_f1_score improved from -inf to 0.56113, saving model to models_ta_task1_m1\best_model_ta_task1_m1.h5


170/170 ━━━━━━━━━━━━━━━━━━━━ 24s 104ms/step - accuracy: 0.5531 - loss: 0.6886 - macro_f1_score: 0.5531 - val_accuracy: 0.5737 - val_loss: 0.6784 - val_macro_f1_score: 0.5737
Epoch 2/15
170/170 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.5536 - loss: 0.6841 - macro_f1_score: 0.5536 
Epoch 2: macro_f1_score improved from 0.56113 to 0.56537, saving model to models_ta_task1_m1\best_model_ta_task1_m1.h5


170/170 ━━━━━━━━━━━━━━━━━━━━ 16s 95ms/step - accuracy: 0.5537 - loss: 0.6841 - macro_f1_score: 0.5537 - val_accuracy: 0.5715 - val_loss: 0.6700 - val_macro_f1_score: 0.5715
Epoch 3/15
170/170 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.5819 - loss: 0.6729 - macro_f1_score: 0.5819 
Epoch 3: macro_f1_score improved from 0.56537 to 0.58436, saving model to models_ta_task1_m1\best_model_ta_task1_m1.h5


170/170 ━━━━━━━━━━━━━━━━━━━━ 16s 96ms/step - accuracy: 0.5819 - loss: 0.6729 - macro_f1_score: 0.5819 - val_accuracy: 0.5715 - val_loss: 0.6684 - val_macro_f1_score: 0.5715
Epoch 4/15
170/170 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.5935 - loss: 0.6606 - macro_f1_score: 0.5935 
Epoch 4: macro_f1_score improved from 0.58436 to 0.59727, saving model to models_ta_task1_m1\best_model_ta_task1_m1.h5


170/170 ━━━━━━━━━━━━━━━━━━━━ 16s 96ms/step - accuracy: 0.5935 - loss: 0.6606 - macro_f1_score: 0.5935 - val_accuracy: 0.5841 - val_loss: 0.6623 - val_macro_f1_score: 0.5841
Epoch 5/15
170/170 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5810 - loss: 0.6659 - macro_f1_score: 0.5810 
Epoch 5: macro_f1_score did not improve from 0.59727
170/170 ━━━━━━━━━━━━━━━━━━━━ 16s 96ms/step - accuracy: 0.5811 - loss: 0.6658 - macro_f1_score: 0.5811 - val_accuracy: 0.5841 - val_loss: 0.6642 - val_macro_f1_score: 0.5841
Epoch 6/15
170/170 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6144 - loss: 0.6504 - macro_f1_score: 0.6144
Epoch 6: macro_f1_score improved from 0.59727 to 0.60465, saving model to models_ta_task1_m1\best_model_ta_task1_m1.h5


170/170 ━━━━━━━━━━━━━━━━━━━━ 18s 106ms/step - accuracy: 0.6144 - loss: 0.6504 - macro_f1_score: 0.6144 - val_accuracy: 0.5892 - val_loss: 0.6612 - val_macro_f1_score: 0.5892
Epoch 7/15
170/170 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6069 - loss: 0.6437 - macro_f1_score: 0.6069 
Epoch 7: macro_f1_score did not improve from 0.60465
170/170 ━━━━━━━━━━━━━━━━━━━━ 18s 108ms/step - accuracy: 0.6069 - loss: 0.6437 - macro_f1_score: 0.6069 - val_accuracy: 0.5767 - val_loss: 0.6690 - val_macro_f1_score: 0.5767
Epoch 8/15
170/170 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.5985 - loss: 0.6506 - macro_f1_score: 0.5985 
Epoch 8: macro_f1_score did not improve from 0.60465
170/170 ━━━━━━━━━━━━━━━━━━━━ 18s 108ms/step - accuracy: 0.5985 - loss: 0.6506 - macro_f1_score: 0.5985 - val_accuracy: 0.5664 - val_loss: 0.6709 - val_macro_f1_score: 0.5664
Epoch 8: early stopping
Restoring model weights from the end of the best epoch: 6.


43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step  

Validation Results:
Precision: 0.5779
Recall: 0.5892
weighted F1 Score: 0.5268
macro F1 Score: 0.4945

Classification Report:
              precision    recall  f1-score   support

    not_hate       0.59      0.89      0.71       778
        hate       0.55      0.18      0.28       578

    accuracy                           0.59      1356
   macro avg       0.57      0.54      0.49      1356
weighted avg       0.58      0.59      0.53      1356



In [13]:
d2 = pd.read_csv('test_ta_l1.csv', engine='python', on_bad_lines='skip')
d2
d2 = d2.rename(columns={'key' : 'unique_id', 'sentence' : 'text'})
d2.to_csv('updated_test_ta_l1.csv', index=False)
# d2
# Convert annotator columns to numeric without replacing NaNs
d2[['ta_a1', 'ta_a2', 'ta_a3', 'ta_a4', 'ta_a5', 'ta_a6']] = d2[
    ['ta_a1', 'ta_a2', 'ta_a3', 'ta_a4', 'ta_a5', 'ta_a6']
].apply(pd.to_numeric, errors='coerce')  # NaNs are retained

# Compute 'label' based on majority voting while ignoring NaNs
d2['label'] = (
    d2[['ta_a1', 'ta_a2', 'ta_a3', 'ta_a4', 'ta_a5', 'ta_a6']].mean(axis=1, skipna=True) >= 0.5
).astype(int)

d2

text   unique_id  ta_a1  \
0        வைரமுத்து ஒரு காம மிருகம் என்பது சினிமா துற...  question_1    NaN   
1     #4YrsOfValiantVIVEGAM  #Valimai #AjithKumar   ...  question_1    0.0   
2     #AmbedkarBlueShirtRally  இந்த போராட்டத்துக்கு ...  question_1    0.0   
3     #BREAKING | திருச்சி மாவட்டம்  மணப்பாறையை அடுத...  question_1    0.0   
4     #Bachelor 😤😤😤😤😤படமாடா இது கோத்தா <handle repla...  question_1    1.0   
...                                                 ...         ...    ...   
1130                                          😂😂😂 ஊம்பு  question_1    1.0   
1131  😄 தமிழ் தெரிஞ்சவன்"தான் உங்கொம்மால குண்டி அடிக...  question_1    1.0   
1132  😅😅😂😂 நீ தான் பங் அவனோலுக்கு கரெக்டா ஆன ஆளு.. 😎...  question_1    NaN   
1133  😺✏ — ஆமாம் வேச ஆமாம் வேச அய்ம் ச்லீபின் அய்ம் ...  question_1    NaN   
1134                 󾓦 :)- Gay  🇱🇰:)- பொடியன் மாஸ்டர் 😂  question_1    NaN   

      ta_a2  ta_a3  ta_a4  ta_a5  ta_a6  label  
0       NaN    0.0    0.0    NaN    0.0      0  
1       NaN    1.0    0.0    NaN    NaN      0  
2       0.0    0.0    NaN    NaN    NaN      0  
3       NaN    0.0    0.0    0.0    0.0      0  
4       0.0    NaN    0.0    NaN    NaN      0  
...     ...    ...    ...    ...    ...    ...  
1130    1.0    NaN    0.0    NaN    NaN      1  
1131    1.0    NaN    NaN    1.0    NaN      1  
1132    NaN    1.0    0.0    NaN    1.0      1  
1133    0.0    NaN    1.0    1.0    NaN      1  
1134    1.0    0.0    1.0    NaN    NaN      1  

[1135 rows x 9 columns]

In [14]:
d2.loc[:, 'binary_label'] = d2['label'].apply(determine_binary_label)

# # Reorder columns
d2 = d2[['unique_id', 'text', 'binary_label', 'label']]

d2.to_csv('updated_test_hi_l1.csv', index=False)

d2.loc[:, 'text'] = d2['text'].apply(lambda x: normalize_text(x))
processed_list = []
for j in d2['text']:
    process = j.replace('...','')
    processed_list.append(process)

df_processed = pd.DataFrame(processed_list)
df_processed.columns = ['text']
df_processed.head(n=5)

X = list(df_processed['text'])
y = d2[['label']].values

X = tokenizer.texts_to_sequences(X)

# Padding
X = pad_sequences(X, padding='post', maxlen=max_len)

y = label_encoder.fit_transform(y.ravel())

y = to_categorical(y, num_classes=2)


In [16]:
test_results = evaluate_validation(trained_model, X, y)

print(r"\Test Results:")
print(f"Precision: {val_results['precision']:.4f}")
print(f"Recall: {val_results['recall']:.4f}")
print(f"weighted F1 Score: {val_results['f1_score_weighted']:.4f}")
print(f"macro F1 Score: {val_results['f1_score_macro']:.4f}")
print("\nClassification Report:")
print(val_results['classification_report'])

36/36 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step
\Test Results:
Precision: 0.5779
Recall: 0.5892
weighted F1 Score: 0.5268
macro F1 Score: 0.4945

Classification Report:
              precision    recall  f1-score   support

    not_hate       0.59      0.89      0.71       778
        hate       0.55      0.18      0.28       578

    accuracy                           0.59      1356
   macro avg       0.57      0.54      0.49      1356
weighted avg       0.58      0.59      0.53      1356

